<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>cr.ac.una</groupId>
  <artifactId>TareaProgramacion3</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>
  <name>TareaProgramacion3</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>21</maven.compiler.release>

    
    <javafx.version>23.0.1</javafx.version>

    
    <jakarta.persistence.version>3.1.0</jakarta.persistence.version>
    <eclipselink.version>4.0.2</eclipselink.version>

    
    <oracle.driver.version>23.4.0.24.05</oracle.driver.version>
  </properties>

  <dependencies>
    
    <dependency>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-controls</artifactId>
      <version>${javafx.version}</version>
      <classifier>win</classifier>
    </dependency>
    <dependency>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-fxml</artifactId>
      <version>${javafx.version}</version>
      <classifier>win</classifier>
    </dependency>
    <dependency>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-graphics</artifactId>
      <version>${javafx.version}</version>
      <classifier>win</classifier>
    </dependency>

   
    <dependency>
      <groupId>jakarta.persistence</groupId>
      <artifactId>jakarta.persistence-api</artifactId>
      <version>${jakarta.persistence.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.persistence</groupId>
      <artifactId>org.eclipse.persistence.jpa</artifactId>
      <version>${eclipselink.version}</version>
    </dependency>

    
    <dependency>
      <groupId>com.oracle.database.jdbc</groupId>
      <artifactId>ojdbc11</artifactId>
      <version>${oracle.driver.version}</version>
      <scope>runtime</scope>
    </dependency>

   
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-math3</artifactId>
      <version>3.6.1</version>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
      <version>2.23.1</version>
    </dependency>

    
    <dependency>
      <groupId>com.sun.xml.ws</groupId>
      <artifactId>jaxws-rt</artifactId>
      <version>4.0.2</version>
    </dependency>
    <dependency>
      <groupId>jakarta.xml.ws</groupId>
      <artifactId>jakarta.xml.ws-api</artifactId>
      <version>4.0.0</version>
    </dependency>
    <dependency>
      <groupId>jakarta.annotation</groupId>
      <artifactId>jakarta.annotation-api</artifactId>
      <version>2.1.1</version>
    </dependency>

    
    <dependency>
      <groupId>jakarta.xml.bind</groupId>
      <artifactId>jakarta.xml.bind-api</artifactId>
      <version>4.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <version>4.0.4</version>
    </dependency>
   
  </dependencies>

  <build>
    <plugins>
     
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
        <configuration>
          <release>${maven.compiler.release}</release>
        </configuration>
      </plugin>

      
      <plugin>
        <groupId>org.openjfx</groupId>
        <artifactId>javafx-maven-plugin</artifactId>
        <version>0.0.8</version>
        <configuration>
          <mainClass>cr.ac.una.tareaprogramacion3.App</mainClass>
        </configuration>
      </plugin>

     
      <plugin>
        <groupId>com.sun.xml.ws</groupId>
        <artifactId>jaxws-maven-plugin</artifactId>
        <version>4.0.2</version>
        <executions>
          <execution>
            <id>wsimport-authws</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>wsimport</goal>
            </goals>
            <configuration>
              <wsdlUrls>
                <wsdlUrl>http://localhost:8080/AuthService/AuthWS?wsdl</wsdlUrl>
              </wsdlUrls>
              <packageName>cr.ac.una.client.soap</packageName>
              <xnocompile>true</xnocompile>
              <vmArgs>
                <vmArg>-Djakarta.xml.accessExternalSchema=all</vmArg>
              </vmArgs>
            </configuration>
          </execution>
          
          <execution>
            <id>wsimport-adminws</id>
            <phase>generate-sources</phase>
            <goals><goal>wsimport</goal></goals>
            <configuration>
              <wsdlUrls>
                <wsdlUrl>http://localhost:8080/AdministradorService/AdministradorWS?wsdl</wsdlUrl>
              </wsdlUrls>
              <packageName>cr.ac.una.client.soap</packageName>
              <xnocompile>true</xnocompile>
              <vmArgs><vmArg>-Djakarta.xml.accessExternalSchema=all</vmArg></vmArgs>
            </configuration>
          </execution>

          <execution>
            <id>wsimport-proyectows</id>
            <phase>generate-sources</phase>
            <goals><goal>wsimport</goal></goals>
            <configuration>
              <wsdlUrls>
                <wsdlUrl>http://localhost:8080/ProyectoService/ProyectoWS?wsdl</wsdlUrl>
              </wsdlUrls>
              <packageName>cr.ac.una.client.soap</packageName>
              <xnocompile>true</xnocompile>
              <vmArgs><vmArg>-Djakarta.xml.accessExternalSchema=all</vmArg></vmArgs>
            </configuration>
          </execution>

          <execution>
            <id>wsimport-actividadws</id>
            <phase>generate-sources</phase>
            <goals><goal>wsimport</goal></goals>
            <configuration>
              <wsdlUrls>
                <wsdlUrl>http://localhost:8080/ActividadService/ActividadWS?wsdl</wsdlUrl>
              </wsdlUrls>
              <packageName>cr.ac.una.client.soap</packageName>
              <xnocompile>true</xnocompile>
              <vmArgs><vmArg>-Djakarta.xml.accessExternalSchema=all</vmArg></vmArgs>
            </configuration>
          </execution>

          <execution>
            <id>wsimport-seguimientows</id>
            <phase>generate-sources</phase>
            <goals><goal>wsimport</goal></goals>
            <configuration>
              <wsdlUrls>
                <wsdlUrl>http://localhost:8080/SeguimientoService/SeguimientoWS?wsdl</wsdlUrl>
              </wsdlUrls>
              <packageName>cr.ac.una.client.soap</packageName>
              <xnocompile>true</xnocompile>
              <vmArgs><vmArg>-Djakarta.xml.accessExternalSchema=all</vmArg></vmArgs>
            </configuration>
          </execution>

          <execution>
            <id>wsimport-reportews</id>
            <phase>generate-sources</phase>
            <goals><goal>wsimport</goal></goals>
            <configuration>
              <wsdlUrls>
                <wsdlUrl>http://localhost:8080/ReporteWSService/ReporteWS?wsdl</wsdlUrl>
              </wsdlUrls>
              <packageName>cr.ac.una.client.soap</packageName>
              <xnocompile>true</xnocompile>
              <vmArgs><vmArg>-Djakarta.xml.accessExternalSchema=all</vmArg></vmArgs>
            </configuration>
          </execution>
        </executions>
      </plugin>

     
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.5.1</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals><goal>shade</goal></goals>
            <configuration>
              <createDependencyReducedPom>false</createDependencyReducedPom>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>cr.ac.una.tareaprogramacion3.App</mainClass>
                </transformer>
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>

    </plugins>
  </build>

</project>