
ALTER SESSION SET CONTAINER = FREEPDB1;


SELECT SYS_CONTEXT('USERENV','CON_NAME') AS con FROM dual;


CREATE USER una IDENTIFIED BY una QUOTA UNLIMITED ON USERS;


GRANT CREATE SESSION TO una;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO una;


ALTER USER una IDENTIFIED BY una ACCOUNT UNLOCK;



