BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_SEGUIMIENTO_PROYECTO_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ACTIVIDAD_ID';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_PROYECTO_ID';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ADMINISTRADOR_ID';         EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SEGUIMIENTO_PROYECTO_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ACTIVIDAD_ID';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PROYECTO_ID';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ADMINISTRADOR_ID';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_GEN_IDENTITY';            EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE SEGUIMIENTO_PROYECTO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ACTIVIDADES CASCADE CONSTRAINTS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROYECTOS CASCADE CONSTRAINTS';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ADMINISTRADORES CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/


CREATE TABLE ADMINISTRADORES (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(80) NOT NULL,
    APELLIDOS VARCHAR2(120) NOT NULL,
    CEDULA VARCHAR2(20) NOT NULL UNIQUE,
    CORREO VARCHAR2(120) NOT NULL UNIQUE,
    USUARIO VARCHAR2(40) NOT NULL UNIQUE,
    PASSWORD_PLAIN VARCHAR2(255) NOT NULL,
    ESTADO VARCHAR2(10) NOT NULL CHECK (ESTADO IN ('ACTIVO','INACTIVO')),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION DATE DEFAULT SYSDATE
);

CREATE TABLE PROYECTOS (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(200) NOT NULL,
    PATROCINADOR_NOMBRE VARCHAR2(120) NOT NULL,
    PATROCINADOR_CORREO VARCHAR2(120) NOT NULL,
    LIDER_USUARIO_NOMBRE VARCHAR2(120) NOT NULL,
    LIDER_USUARIO_CORREO VARCHAR2(120) NOT NULL,
    LIDER_TECNICO_NOMBRE VARCHAR2(120) NOT NULL,
    LIDER_TECNICO_CORREO VARCHAR2(120) NOT NULL,
    FECHA_INICIO_PLANIFICADA DATE NOT NULL,
    FECHA_FINAL_PLANIFICADA DATE NOT NULL,
    FECHA_INICIO_REAL DATE,
    FECHA_FINAL_REAL DATE,
    ESTADO VARCHAR2(20) NOT NULL CHECK (ESTADO IN ('PLANIFICADO','EN_CURSO','SUSPENDIDO','FINALIZADO')),
    PORCENTAJE_AVANCE NUMBER(3,0) DEFAULT 0 CHECK (PORCENTAJE_AVANCE BETWEEN 0 AND 100),
    DESCRIPCION CLOB,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION DATE DEFAULT SYSDATE,
    CREADO_POR NUMBER,
    CONSTRAINT FK_PROYECTO_CREADO_POR FOREIGN KEY (CREADO_POR) REFERENCES ADMINISTRADORES(ID)
);

CREATE TABLE ACTIVIDADES (
    ID NUMBER PRIMARY KEY,
    PROYECTO_ID NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(500) NOT NULL,
    ENCARGADO_NOMBRE VARCHAR2(120) NOT NULL,
    ENCARGADO_CORREO VARCHAR2(120) NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL CHECK (ESTADO IN ('PLANIFICADA','EN_CURSO','POSTERGADA','FINALIZADA')),
    FECHA_INICIO_PLANIFICADA DATE NOT NULL,
    FECHA_FINAL_PLANIFICADA DATE NOT NULL,
    FECHA_INICIO_REAL DATE,
    FECHA_FINAL_REAL DATE,
    ORDEN_EJECUCION NUMBER NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ACTIVIDAD_PROYECTO FOREIGN KEY (PROYECTO_ID) REFERENCES PROYECTOS(ID) ON DELETE CASCADE
);

CREATE TABLE SEGUIMIENTO_PROYECTO (
    ID NUMBER PRIMARY KEY,
    PROYECTO_ID NUMBER NOT NULL,
    FECHA_SEGUIMIENTO DATE NOT NULL,
    OBSERVACIONES CLOB NOT NULL,
    PORCENTAJE_AVANCE NUMBER(3,0) NOT NULL CHECK (PORCENTAJE_AVANCE BETWEEN 0 AND 100),
    CREADO_POR NUMBER NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    CONSTRAINT FK_SEGUIMIENTO_PROYECTO FOREIGN KEY (PROYECTO_ID) REFERENCES PROYECTOS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SEGUIMIENTO_CREADO_POR FOREIGN KEY (CREADO_POR) REFERENCES ADMINISTRADORES(ID)
);


CREATE SEQUENCE SEQ_ADMINISTRADOR_ID      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PROYECTO_ID           START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ACTIVIDAD_ID          START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SEGUIMIENTO_PROYECTO_ID START WITH 1 INCREMENT BY 1 NOCACHE;


CREATE SEQUENCE SEQ_GEN_IDENTITY          START WITH 1 INCREMENT BY 1 NOCACHE;


CREATE OR REPLACE TRIGGER TRG_ADMINISTRADOR_ID
BEFORE INSERT ON ADMINISTRADORES
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN :NEW.ID := SEQ_ADMINISTRADOR_ID.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PROYECTO_ID
BEFORE INSERT ON PROYECTOS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN :NEW.ID := SEQ_PROYECTO_ID.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ACTIVIDAD_ID
BEFORE INSERT ON ACTIVIDADES
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN :NEW.ID := SEQ_ACTIVIDAD_ID.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_SEGUIMIENTO_PROYECTO_ID
BEFORE INSERT ON SEGUIMIENTO_PROYECTO
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN :NEW.ID := SEQ_SEGUIMIENTO_PROYECTO_ID.NEXTVAL; END IF;
END;
/


CREATE INDEX IDX_PROYECTO_ESTADO ON PROYECTOS(ESTADO);
CREATE INDEX IDX_PROYECTO_FECHAS ON PROYECTOS(FECHA_INICIO_PLANIFICADA, FECHA_FINAL_PLANIFICADA);
CREATE INDEX IDX_ACTIVIDAD_PROYECTO ON ACTIVIDADES(PROYECTO_ID);
CREATE INDEX IDX_ACTIVIDAD_ORDEN ON ACTIVIDADES(PROYECTO_ID, ORDEN_EJECUCION);
CREATE INDEX IDX_SEGUIMIENTO_PROYECTO ON SEGUIMIENTO_PROYECTO(PROYECTO_ID);
CREATE INDEX IDX_SEGUIMIENTO_FECHA ON SEGUIMIENTO_PROYECTO(FECHA_SEGUIMIENTO);


INSERT INTO ADMINISTRADORES (NOMBRE, APELLIDOS, CEDULA, CORREO, USUARIO, PASSWORD_PLAIN, ESTADO)
VALUES ('Admin','Sistema','123456789','admin@una.ac.cr','admin','admin123','ACTIVO');

DECLARE
  v_max  NUMBER := 0;
  v_curr NUMBER;
BEGIN
  SELECT GREATEST(
           NVL((SELECT MAX(ID) FROM ADMINISTRADORES), 0),
           NVL((SELECT MAX(ID) FROM PROYECTOS), 0),
           NVL((SELECT MAX(ID) FROM ACTIVIDADES), 0),
           NVL((SELECT MAX(ID) FROM SEGUIMIENTO_PROYECTO), 0)
         ) + 1
    INTO v_max
    FROM DUAL;

  BEGIN
    SELECT SEQ_GEN_IDENTITY.CURRVAL INTO v_curr FROM DUAL;
  EXCEPTION WHEN OTHERS THEN
    SELECT SEQ_GEN_IDENTITY.NEXTVAL INTO v_curr FROM DUAL;
  END;

  IF v_curr < v_max THEN
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_GEN_IDENTITY INCREMENT BY '||(v_max - v_curr);
    SELECT SEQ_GEN_IDENTITY.NEXTVAL INTO v_curr FROM DUAL; -- aplica el salto
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_GEN_IDENTITY INCREMENT BY 1';
  END IF;
END;
/

COMMIT;
